"""Create the initial CONVOSIS CRM schema."""

from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def timestamps() -> tuple[sa.Column, sa.Column]:
    return (sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))


def upgrade() -> None:
    op.create_table("approval_processes", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("module", sa.String(50), nullable=False), sa.Column("trigger", sa.String(180), nullable=False), sa.Column("approver", sa.String(120), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.Column("conditions", sa.JSON()), sa.Column("steps", sa.JSON()), *timestamps())
    op.create_table("blueprints", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("module", sa.String(50), nullable=False), sa.Column("entry_criteria", sa.Text()), sa.Column("stages", sa.JSON()), sa.Column("transitions", sa.JSON()), sa.Column("transition_requirements", sa.JSON()), sa.Column("active", sa.Boolean(), nullable=False))
    op.create_table("organization_settings", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("org_name", sa.String(160), nullable=False), sa.Column("timezone", sa.String(80), nullable=False), sa.Column("currency", sa.String(10), nullable=False), sa.Column("date_format", sa.String(30), nullable=False), sa.Column("fiscal_year_start", sa.String(20), nullable=False), sa.Column("default_pipeline", sa.String(80), nullable=False), sa.Column("notifications", sa.JSON()))
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("email", sa.String(180), nullable=False, unique=True), sa.Column("role", sa.String(80), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.Column("last_active", sa.DateTime()), *timestamps())
    op.create_table("accounts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(180), nullable=False), sa.Column("website", sa.String(180)), sa.Column("phone", sa.String(40)), sa.Column("industry", sa.String(100)), sa.Column("employees", sa.Integer()), sa.Column("annual_revenue", sa.Float()), sa.Column("type", sa.String(60)), sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("billing_city", sa.String(100)), sa.Column("billing_country", sa.String(100)), sa.Column("status", sa.String(30), nullable=False), sa.Column("notes", sa.Text()), sa.Column("tags", sa.JSON()), sa.Column("archived", sa.Boolean(), nullable=False), *timestamps())
    op.create_table("activities", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("activity_type", sa.String(30), nullable=False), sa.Column("subject", sa.String(180), nullable=False), sa.Column("start_at", sa.DateTime()), sa.Column("due_at", sa.DateTime()), sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("status", sa.String(30), nullable=False), sa.Column("priority", sa.String(30), nullable=False), sa.Column("related_type", sa.String(40)), sa.Column("related_id", sa.Integer()), sa.Column("description", sa.Text()), sa.Column("completed_at", sa.DateTime()), sa.Column("archived", sa.Boolean(), nullable=False), *timestamps())
    op.create_table("attachments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(180), nullable=False), sa.Column("file_type", sa.String(80)), sa.Column("file_size", sa.String(40)), sa.Column("url", sa.String(500)), sa.Column("related_type", sa.String(40)), sa.Column("related_id", sa.Integer()), sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("archived", sa.Boolean(), nullable=False), *timestamps())
    op.create_table("emails", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("subject", sa.String(220), nullable=False), sa.Column("from_email", sa.String(180)), sa.Column("to_email", sa.String(180)), sa.Column("body", sa.Text()), sa.Column("status", sa.String(30), nullable=False), sa.Column("sent_at", sa.DateTime()), sa.Column("related_type", sa.String(40)), sa.Column("related_id", sa.Integer()), sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("archived", sa.Boolean(), nullable=False), *timestamps())
    op.create_table("notes", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("title", sa.String(180), nullable=False), sa.Column("content", sa.Text()), sa.Column("related_type", sa.String(40)), sa.Column("related_id", sa.Integer()), sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("archived", sa.Boolean(), nullable=False), *timestamps())
    op.create_table("products", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(180), nullable=False), sa.Column("sku", sa.String(80)), sa.Column("category", sa.String(100)), sa.Column("unit_price", sa.Float(), nullable=False), sa.Column("stock_quantity", sa.Integer(), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.Column("description", sa.Text()), sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("related_type", sa.String(40)), sa.Column("related_id", sa.Integer()), sa.Column("archived", sa.Boolean(), nullable=False), *timestamps())
    op.create_table("contacts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("first_name", sa.String(100), nullable=False), sa.Column("last_name", sa.String(100), nullable=False), sa.Column("email", sa.String(180)), sa.Column("phone", sa.String(40)), sa.Column("job_title", sa.String(120)), sa.Column("department", sa.String(100)), sa.Column("account_id", sa.Integer(), sa.ForeignKey("accounts.id")), sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("notes", sa.Text()), sa.Column("tags", sa.JSON()), sa.Column("archived", sa.Boolean(), nullable=False), *timestamps())
    op.create_table("deals", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(180), nullable=False), sa.Column("account_id", sa.Integer(), sa.ForeignKey("accounts.id")), sa.Column("contact_id", sa.Integer(), sa.ForeignKey("contacts.id")), sa.Column("amount", sa.Float(), nullable=False), sa.Column("stage", sa.String(80), nullable=False), sa.Column("probability", sa.Integer(), nullable=False), sa.Column("expected_close_date", sa.Date()), sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("type", sa.String(60)), sa.Column("source", sa.String(80)), sa.Column("status", sa.String(30), nullable=False), sa.Column("notes", sa.Text()), sa.Column("archived", sa.Boolean(), nullable=False), *timestamps())
    op.create_table("leads", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("company", sa.String(160)), sa.Column("email", sa.String(180)), sa.Column("phone", sa.String(40)), sa.Column("source", sa.String(80)), sa.Column("status", sa.String(40), nullable=False), sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("lead_score", sa.Integer(), nullable=False), sa.Column("next_follow_up", sa.Date()), sa.Column("notes", sa.Text()), sa.Column("tags", sa.JSON()), sa.Column("archived", sa.Boolean(), nullable=False), sa.Column("converted_account_id", sa.Integer(), sa.ForeignKey("accounts.id")), sa.Column("converted_contact_id", sa.Integer(), sa.ForeignKey("contacts.id")), sa.Column("converted_deal_id", sa.Integer(), sa.ForeignKey("deals.id")), *timestamps())


def downgrade() -> None:
    for table_name in ("leads", "deals", "contacts", "products", "notes", "emails", "attachments", "activities", "accounts", "users", "organization_settings", "blueprints", "approval_processes"):
        op.drop_table(table_name)
